Feat/153 make build and push always sync
inpsyde/reusable-workflows pull request #154
Opened 2024-08-22 15:33 UTC by luislard

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)

**What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

**Other information**:

2024-08-27 09:26 UTC, Chrico approved these changes

2024-08-27 14:26 UTC, tyrann0us requested changes

2024-08-27 14:26 UTC, tyrann0us commented on .github/workflows/build-and-push-assets.yml
>            git commit -m "[BOT] Add compiled assets for #${{ github.ref }}" --no-verify || ((echo "NO_CHANGES=yes" >> $GITHUB_ENV) && (echo "No changes to commit"))
The `NO_CHANGES` env variable is no longer used, so we don't have to populate it here (untested!).
```suggestion
          git commit -m "[BOT] Add compiled assets for #${{ github.ref }}" --no-verify || echo "No changes to commit"
```
Please also remove it from line 148 and remove the unused `LOCK_FILE` env variable according to the Boy Scout rules. Thanks!

2024-09-02 09:15 UTC, shvlv approved these changes

2024-09-02 09:31 UTC, tyrann0us approved these changes
Haven't tested this but code-wise LGTM.
Could you please remove `LOCK_FILE` from line 147 according to the Boy Scout rule? Thanks!

2024-09-02 09:31 UTC, tyrann0us commented on .github/workflows/build-and-push-assets.yml
>            git commit -m "[BOT] Add compiled assets for #${{ github.ref }}" --no-verify || ((echo "NO_CHANGES=yes" >> $GITHUB_ENV) && (echo "No changes to commit"))
Obsolete with the latest amendments.

2024-09-04 08:53 UTC, tyrann0us approved these changes
Cool, thanks!

2024-09-04 08:53 UTC, merged